{% set version = '1.0.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nycflights13
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nycflights13_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nycflights13/nycflights13_{{ version }}.tar.gz
  sha256: 1626cae2329e23343fe797553c5a2af341cf7abe31d3545ca45bfb783b2b6081

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: dplyr
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-tibble

  run:
    - r-base
    - r-tibble

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('nycflights13')"           # [not win]
    - "\"%R%\" -e \"library('nycflights13')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/hadley/nycflights13
  license: CC0
  summary: Airline on-time data for all flights departing NYC in 2013. Also includes useful 'metadata'
    on airlines, airports, weather, and planes.
  license_family: CC

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: nycflights13
# Title: Flights that Departed NYC in 2013
# Version: 1.0.0
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre")), person("RStudio", role = "cph") )
# Description: Airline on-time data for all flights departing NYC in 2013. Also includes useful 'metadata' on airlines, airports, weather, and planes.
# License: CC0
# URL: http://github.com/hadley/nycflights13
# BugReports: https://github.com/hadley/nycflights13/issues
# Depends: R (>= 2.10)
# Imports: tibble
# Suggests: dplyr
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-06-26 17:30:08 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-06-26 17:39:38 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
