# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "l4nc07curUG3uXVMJVS76fBoUjdGtWVBYswYvQZSyi9Y5AFD+XJ9O/s1NZvmF6datIkAPIPZHWqw/SEI+U+GPziVrt0RpHIW5fLh8o0Ls0PbOzTDoDpkQrVffzktg5leVJxTo+bL4ngojEcf3GSJlGB9y66zbV51/OUa5kLr3VbKlnlHDfhoSW3dRWsFKdlL6uLwYUuOgJtj9hOgGFatL0mZ65MJphePTpY+6eTMimF5ok6O/VHYOWoDHHAbbXqUweOvYEP1qJryxjzUHd3l7JIY808Nj1MYSLErnqVCcKcxYdF2k9lOWpAOiL9hzVCXiHG0MOeGFbcmCUklEQS2fbSOc3FHf8krSo+yQ28fZfqaCvF6Ub/gwV8iXZEZ1U5D7fgB9Tx2oqMtSf8C87sbvqNw6tjHRcR0anO9dHsDzeQocOYfCZnR5CubHlxYn3cLURnj2Fid5CeygLue9dD0Eszo6p1ZYozMaLfqOCM+UOu06kWb5iFqPkBoq1c844+g20VM5A4jVFedU9Xu1H7KcNQ3UCv3cynuX33OV10M7XRSZgsrhXxbxavbepj8ik0d6aMRmp5WfOLXO+DEEfSr2Rtqz/YkgteZBTqlE9D/NMfzfQpMm4j+sEsnSWfzA1ws0qoUzusr9X/RM6xvxDqOvJU3zGOwuHPrdnOdmGYnGdI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
