travis:
  secure:
    BINSTAR_TOKEN: JtItLMgbkF/t5jcTGw2YtlR++Cfczj5y7U1hWU4HplssYiW0fmaN4SSd0JNJ1f8xszVh5mIY6So0KL7C6dVAL/u2iOiA4Elj40aWW4bqYrX16dqBKrawcqs4UD3gV8MR+/Py8W1a4Hvdx5ZB10+0U1J08qMld7WvjpwbsUzOTaljUpxMFGq+4J+kow/tZzD7SkOKl4Xt0ffUukqLfIRyjgglGWIrzi6Qo4F2LbYmF3OCxPaNtzP6D63S52dhfANpX/c92XIL07q/4o77NNhzHFQ8VI/b8KtIVfHuk3GugoEvfiZ9Muxnh9OkDTqiyI61KEoVa1VsY33QeBCjXkTkjD/iy0gksdH6jxvf9rDzIqP6YP2xkJPdqagrIZMCWMOWR5zj/NFLMUqOBFQFiiZ8Kn3SXQzg+mkSyjEzyzw2QPqXea732ve7TXZOuZLs8sIvUiH+aZa8RyWIA/tm1z0umwIa92UNUMrr768m4DMXg7m7cTuyYQYnv0ywdqZs+2SDry1bejLFyyQ2+50sXM+GISoIqNlrYrc6siS6cvMac3SkXvnpoCrHQy/SnfPoEFRja+pWHg8xonahXzTwyrNhqLt0XPtc17wWJEabQ23s2/m62j83jbjdVROq0+6LNHrluRP6ooOnFFJQRVAjFEoLiJ0QSP05KapTJaGiZvPXFS8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
