travis:
  secure:
    BINSTAR_TOKEN: ne5DuG6iwVv/xWeODetHLzDVv+3TYDI6vRYJJC2NlRps2hNwZWPPsTXDaV5c6XaWZcELws6H/0JEi9cG5XrlMTXf+jzqPKffVaNRMmpnzO6BAqUoLDA8utut+BgjdiugQoyI2kKbuBh0mDOYHBXrtaDefuvafZNksq3E4USFijoQBIyBpD034fuMmuWWr9csMxScbueMs644qoSvi/yT+wl7q25xZi1/fbzOzkknNWyxYEZbJqQI0101ZJPRgLejsz1ik30V4rgqLSMyny+BANG8tj2kUnBlBOppeTInrm9l62mJISOygEe17jurgklQqTG8aNgIbCeC3zWruI2JYaA+LhRGEatiA1aCrm8nEicX01Lxy2eKF5QW7yHTxAAheBTnUoYosezxTmtzCfdRJufBsfRjVoR0nFCadnpd12lNjuNPURo2mYxVTafLbtqjc3IZZUcacts5KRRLpfC4ahsPZsPWQrcVtx409MYh+FU/2o3DoVl7IlgrMzwHI3jPX2DCdYe0moK0lTNXziR8gzqUzv80nZDTsHJ7hhQEDdQm0Ox6Kys1MbunkrpaMwhw/QzEc1th6HOlnbQgoig1QbzWGwtEZc8v8qcNbeWCnMiC0tjcwAG6jDIXEtzjdkttMdmsRpuKDBYlrL2MWyLVHuTgtfof57Oc+A32Ws2EXmY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
